# Generated by Django 4.2.11 on 2024-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("D", "Donor"), ("N", "Nurse")],
                max_length=255,
                null=True,
            ),
        ),
    ]
