# Generated by Django 4.2.11 on 2024-04-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_hospitalsettings_alter_customuser_gender_bloodbag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodbag",
            name="expiration_date",
            field=models.DateField(blank=True, help_text="Auto calculated if null"),
        ),
    ]
