# Generated by Django 4.2.6 on 2024-07-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='feedLogo')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='physicalTherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='physicalTherapyLogo')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='section_img')),
            ],
        ),
        migrations.CreateModel(
            name='sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='sportImageLogo')),
                ('type', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.section')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('favouritesports', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='sportsvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='sports_video')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sports')),
            ],
        ),
        migrations.CreateModel(
            name='sportsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='sportImage')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sports')),
            ],
        ),
        migrations.CreateModel(
            name='sportsclub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sports')),
            ],
        ),
        migrations.CreateModel(
            name='sportadvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(max_length=100)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sports')),
            ],
        ),
        migrations.CreateModel(
            name='physicalvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='physicalvideo')),
                ('physical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.physicaltherapy')),
            ],
        ),
        migrations.AddField(
            model_name='physicaltherapy',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.section'),
        ),
        migrations.CreateModel(
            name='physicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='physicalImage')),
                ('physical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.physicaltherapy')),
            ],
        ),
        migrations.CreateModel(
            name='physicalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('physical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.physicaltherapy')),
            ],
        ),
        migrations.CreateModel(
            name='physicaladvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(max_length=100)),
                ('physical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.physicaltherapy')),
            ],
        ),
        migrations.CreateModel(
            name='feedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='physicalImage')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.feed')),
            ],
        ),
        migrations.CreateModel(
            name='feedadvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(max_length=100)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.feed')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.section'),
        ),
    ]
