# Generated by Django 4.2.11 on 2024-04-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_termquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="warn_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
